### ISSUE TITLE
Falied to compile

### ISSUE THREAD

**Issue by rybakchuj1** [Portaler-Zone/portaler-core#116]
Hey, i set up everythink like in the guide but i got a error while entering the page, can u help me guys?

![image](https://user-images.githubusercontent.com/103209949/162439807-1a531ae7-29f3-46d2-9fe4-f938feb35b12.png)

**Comment by mawburn** [comment]
Please direct these questions to Discord.

https://discord.gg/3GwNSgvR5g

Thanks.
