### ISSUE TITLE
Missing Hideout zones

### ISSUE THREAD

**Issue by Kazine** [Portaler-Zone/portaler-core#12]
So I copied your zones.js file, and was comparing them to ones that we had in a spreadsheet with map images ( From testing server and when roads began). I wasn't sure if they were still in the game until I tried to Map Secent-Qinsom but it wasnt in Portaler 

These are ones missing:  
Qiient-Nusas
Qiient-Nusom
Qiient-Odetis
Qiient-Odetum
Qiient-Qinsis
Qiient-Tersas
Qiient-Tertum
Qiient-Viesis
Qiient-Vynsis
Qiitun-Vynsom
Quaent-Nusis
Secent-Odesis
Secent-Qinsas
Secent-Qinsom
Secent-Tersum
Sectun-Odesis
Sectun-Vyntis
Setent-Qinsum
Settun-Nusis
Settun-Odeitum

**Comment by mawburn** [comment]
This is great, thank you. I'll definitely get these added. The data I think needs updating, but I personally haven't ran into anything that doesn't exist yet.
