### ISSUE TITLE
error Command failed with exit code 1.

### ISSUE THREAD

**Issue by Biozxx** [Portaler-Zone/portaler-core#13]
```
C:\WINDOWS\system32>yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "babel-eslint@10.x".
warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "eslint-plugin-flowtype@3.x || 4.x".
warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@6.x".
warning " > eslint-config-react-app@5.2.1" has incorrect peer dependency "eslint-plugin-react-hooks@1.x || 2.x".
warning " > eslint-webpack-plugin@2.2.1" has incorrect peer dependency "eslint@^7.0.0".
warning " > eslint-webpack-plugin@2.2.1" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 1.44s.

C:\WINDOWS\system32>yarn dev:front
yarn run v1.22.5
$ cd packages/frontend && yarn start
O sistema não pode encontrar o caminho especificado.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I downloaded your zip and dragged the package.json to system32, is that right? 

I have yan and node installed, I also did yan upgrade.

![image](https://user-images.githubusercontent.com/70315679/98753598-797feb80-23a3-11eb-81f5-c3a5336eb6c4.png)

Sorry I amm reading guides and learning how to use Yan and etc so I am a bit lost here.

I tried the go mod download and it says no modules specified, so I tried adding docker-compose up -d db and it says its not a know dependency.

@mawburn

**Comment by mawburn** [comment]
@Biozxx I didn't really develop it to be run on Windows. But, you probably shouldn't be dragging it into your system32 folder. Try another folder somewhere else, like Documents or something along those lines. 

I'd also recommend using the Ubuntu Subsystem or GitBash or even a Linux VM. Portaler isn't developed to work with Windows and there aren't any plans to make it Windows compatible.

**Comment by Biozxx** [comment]
Oh, why not?

Ok, I will try learning about linux subsystems.

**Comment by mawburn** [comment]
It's just not something where the code needs to be deployed. I'll probably put a docker build in for the frontend eventually, which would help (assuming Docker isn't a PitA on Windows too), but it's still early in the project.

**Comment by mawburn** [comment]
@Biozxx have you tried the new local version?

https://github.com/Portaler-Zone/portaler-core/tree/main/local
