### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Kazine** [Portaler-Zone/portaler-core#6]
- I like the Mats information, maybe add what type of chests and dungeons in zone
- if the connections that don't connect to set home  after a portal disappears  , it removes the chain. ( turn on/off incase the person wants to map more than just their connections ). Another is an option to select and delete paths.
- I like to move connections so that they start from the direction the portal platform is from hide out, a way to set that would be nice. ( When a connection closes it will move the placement of the roads , would be a nice way to lock it down)
Before Portal Closes:
![image](https://user-images.githubusercontent.com/62967533/98178770-ec302900-1ec2-11eb-82e7-25e28adff844.png)
After Portal Closes:
![image](https://user-images.githubusercontent.com/62967533/98178835-0ec24200-1ec3-11eb-9c65-d863b9e77d5e.png)

**Comment by mawburn** [comment]
> I like the Mats information, maybe add what type of chests and dungeons in zone

This is definitely on the list to be added. 

> if the connections that don't connect to set home after a portal disappears , it removes the chain. ( turn on/off incase the person wants to map more than just their connections ). 

Yeah this would have to be a toggle, but definitely doable.

> Another is an option to select and delete paths.

On our list for sure. 

> I like to move connections so that they start from the direction the portal platform is from hide out, a way to set that would be nice. ( When a connection closes it will move the placement of the roads , would be a nice way to lock it down)

Unfortunately, with the graphing library that I'm using this isn't easily possible. It could probably be done, but it might be far down the list in terms of priority.

**Comment by Kazine** [comment]
> I like the Mats information, maybe add what type of chests and dungeons in zone
> 
>  >This is definitely on the list to be added.
 
Hopefully helpful here is copy of an [excel sheet](https://docs.google.com/spreadsheets/d/1ibaQfvCjrIeBVhJn8gy3U15YPwtePl3T0F99l74a9rA/edit?usp=sharing) that I marked what each zone has based on the map. The ones highlighted in cyan are the zones I didn't have maps of to check.

**Comment by mawburn** [comment]
Oh very nice, that will probably be very useful. A lot of what we've relied on is the Albion dumps repo. 

https://github.com/broderickhyman/ao-bin-dumps

Which were compiled here:

https://raw.githubusercontent.com/Tebro/albion-mapper-backend/master/data-dump.json

So we actually have the data for the _markers_, I'm just not showing them atm. I'll probably rework this soon.

**Comment by mawburn** [comment]
> if the connections that don't connect to set home after a portal disappears , it removes the chain. ( turn on/off incase the person wants to map more than just their connections ). Another is an option to select and delete paths.

What if this was just a toggle? Like at the UI level only. This way it could be on an individual basis and you could still retain your connections in case you get lost. I think this would be much easier to implement and better for the user. 

I could also play with a toggle that just turned the opacity way down on connections that aren't connected to home. 

@Kazine what are your thoughts on this?

**Comment by Kazine** [comment]
A toggle sounds like a good idea, same with the opacity

**Comment by Kazine** [comment]
Another Suggestion: A way to color zones that are not in the roads that way we can distinguish which connections are in the roads and which arent.  Would have been helpful when tracking way back to HO after content to know the difference
![image](https://user-images.githubusercontent.com/62967533/99299641-1cf05680-2811-11eb-90a4-c5a0d0240ff8.png)

**Comment by mawburn** [comment]
@Kazine yep, I plan on adding a royal connections option as soon as I finish up this PR https://github.com/Portaler-Zone/portaler-core/pull/15

**Comment by mawburn** [comment]
One of my long term goals is to figure out a way to get all the royal to royal connections and have them auto populate when you find portals adjacent to each other. But as a first step, it'll be manual.
