### ISSUE TITLE
User being inserted in database, but user_roles and user_servers no

### ISSUE THREAD

**Issue by SandroMoretti** [Portaler-Zone/portaler-core#99]
Hi!

I'm trying to self hosting in an VPS.
I followed the steps on https://github.com/Portaler-Zone/portaler-core/blob/main/docs/selfhosting.md docs.

I got sucessfully made the app run, the bot joined my server and created "portaler" role, I also have added my subdomain using the admin api.

When I try to login I dont receive the subdomain error anymore, so I guess my configurations its okay... But I'm receving token=/invalid.

I checked in code and this happen when portaler select user from database but no user is returned.

Then I logged in in psql console and used some querys to test. Thats strange cause when I try to login portaler its inserting my user in table ```users```, table ```servers``` is inserted too:

![image](https://user-images.githubusercontent.com/6597833/141506798-9f25d10a-8873-4cf1-a871-c2e4a14067bf.png)

But tables ```user_servers``` and ```user_roles``` have nothing:

![image](https://user-images.githubusercontent.com/6597833/141506921-5664c873-4980-48ce-b46a-493ef7896e17.png)

In my api logs don't have any error anymore. When I try to login I dont receive no errors, just token=invalid in my redirect url.

Maybe thats an permission issue? My bot already have the ```role manager``` permission, I'm sure of that cause he created portaler role in my server.

My discord bot is configured like:

![image](https://user-images.githubusercontent.com/6597833/141507267-52251dd2-5590-4c1b-9058-987d173ccf42.png)

I know that bot need this configs to list all ppl in discord guild, so I already activated it (even that is not in docs).

I dont know more configurations to do. I was trying to edit code to put some debugs but I dont know how to put my edited code in docker container so I come here.

Does anyone know any reason for this problem? Thanks

**Comment by ImmortalBrain** [comment]
I might be wrong, but afaik user_roles and user_servers get populated when you actually grant someone the created "portaler" role.
If it didn't populate, try removing the role (but don't delete it completely!) from someone and adding it back, this should populate the DB and allow the user to log-in

**Comment by SandroMoretti** [comment]
> I might be wrong, but afaik user_roles and user_servers get populated when you actually grant someone the created "portaler" role.
> If it didn't populate, try removing the role (but don't delete it completely!) from someone and adding it back, this should populate the DB and allow the user to log-in



Hello. Thank you for you ansewer, but it populate these tables in auth process.
When user try to login, the system insert the user, then insert the user server and finally insert the user role... I see this in auth.ts calling User.ts insert function... The same finction that insert the user insert the other tables too, so probally this function is catching some error, but dont have logger in User.ts so I cant see the error :(

Anyway I'll try you suggestion too, maybe the bot process the roles and insert too, so I'll try. Thank you

**Comment by SandroMoretti** [comment]
You're right. The auth code in api insert the role and server table, but the bot does it too. When I try to do what u did worked fine. Thanks @ImmortalBrain

**Comment by SandroMoretti** [comment]
The "Forbidden" error is caused to apache httpd, when it redirect from /api to port 7777 the cookie is not received by the api.

I'll try to find an way to configure apache too and if I got it I'll post here

**Comment by SandroMoretti** [comment]
I got it.
If someone need to run in apache / httpd, use the follow configurations:

nano /etc/httpd/conf.d/gps-portaler.conf

```
<VirtualHost SUBDOMAIN_HERE:80>
        ServerName http://SUBDOMAIN_HERE
        ServerAlias SUBDOMAIN_HERE
        DocumentRoot "/usr/local/etc/docker-portaler/portaler-core/packages/frontend/build/"
        ProxyPreserveHost On
        ProxyPass /api http://localhost:7777/api
        ProxyPassReverse /api http://localhost:7777/api
</VirtualHost>
```

My problem was missing option ```ProxyPreserveHost On``` in configuration.
